<a href="https://colab.research.google.com/github/JITHINJITH/AI-LAB/blob/master/Naive_Bayes_classifier_on_Kaggle_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
heart = pd.read_csv('/content/heart.csv')
x = heart.iloc[:,:-1].values
y = heart.iloc[:,-1].values
heart.head()


age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [10]:
y_pred = np.random.randint(low=0,high=100,size=(1,13))

In [11]:
from sklearn.naive_bayes import BernoulliNB
bn = BernoulliNB()
bn.fit(x,y)
bn.predict(y_pred)

array([0])

In [14]:
from sklearn.metrics import accuracy_score
acc1 = accuracy_score(y,bn.predict(x))
print('Accuracy is ',acc1*100)

Accuracy is  83.16831683168317


In [12]:
from sklearn.naive_bayes import GaussianNB
gn = GaussianNB()
gn.fit(x,y)
gn.predict(y_pred)

array([1])

In [15]:
from sklearn.metrics import accuracy_score
acc2 = accuracy_score(y,gn.predict(x))
print('Accuracy is ',acc2*100)

Accuracy is  84.15841584158416


In [13]:
from sklearn.naive_bayes import MultinomialNB
mn = MultinomialNB()
mn.fit(x,y)
mn.predict(y_pred)

array([1])

In [16]:
from sklearn.metrics import accuracy_score
acc3 = accuracy_score(y,mn.predict(x))
print('Accuracy is ',acc3*100)

Accuracy is  75.24752475247524
