<a href="https://colab.research.google.com/github/JITHINJITH/AI-LAB/blob/master/Naive_Bayes_classifier_on_load_iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
x = iris.data
y = iris.target

In [ ]:
from sklearn.naive_bayes import BernoulliNB
bn = BernoulliNB()
bn.fit(x,y)
bn.predict([[1,2,3,4.5]])

array([0])

In [ ]:
from sklearn.naive_bayes import GaussianNB
gn = GaussianNB()
gn.fit(x,y)
gn.predict([[1,2,3,4.5]])

array([2])

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mn = MultinomialNB()
mn.fit(x,y)
mn.predict([[1,2,3,4.5]])

array([2])