In [1]:
import numpy as np
import pandas as pd


In [25]:
from sklearn.datasets import load_iris
iris = load_iris()
x=iris.data
y=iris.target

In [26]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

ML1=GaussianNB()
ML2 = MultinomialNB()
ML3 = BernoulliNB()


In [29]:
ML1 =ML1.fit(x,y)
ML2 =ML2.fit(x,y)
ML3 =ML3.fit(x,y)

In [32]:
op1 = ML1.predict([[3.5,3.5,3.5,3.5 ]])
op1

array([2])

In [33]:
op2 = ML2.predict([[3.5,3.5,3.5,3.5 ]])
op2

array([2])

In [34]:
op3 = ML3.predict([[3.5,3.5,3.5,3.5 ]])
op3

array([0])